// src/ui-components/web-components/snackbar.ts
/*
 * SPDX-FileCopyrightText: 2025 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import './icon-wc';

import { html, LitElement, nothing } from 'lit';
import { property } from 'lit/decorators.js';
import { styleMap } from 'lit/directives/style-map.js';

import { resolveThemeColor } from '../theme/theme-utils';
import { type IconName } from './icon-registry';
import { snackbarStyles } from './snackbar.styles';

const DEFAULT_HIDE_TIMEOUT = 4000;

const icons: Record<'success' | 'info' | 'warning' | 'error', IconName> = {
  success: 'CheckmarkOutline',
  info: 'InfoOutline',
  warning: 'AlertTriangleOutline',
  error: 'CloseCircleOutline',
};

type SnackbarSeverity = 'success' | 'info' | 'warning' | 'error';

export class ZxSnackbar extends LitElement {
  static override styles = snackbarStyles;

  @property({ type: Boolean, reflect: true })
  accessor open = false;

  @property({ type: String, reflect: true })
  accessor severity: SnackbarSeverity = 'info';

  @property({ type: String })
  accessor label = '';

  @property({ type: String, attribute: 'action-label' })
  accessor actionLabel = 'Ok';

  @property({ type: Number, attribute: 'auto-hide-timeout' })
  accessor autoHideTimeout = DEFAULT_HIDE_TIMEOUT;

  private timeoutId: number | undefined;

  private handleClose(): void {
    this.dispatchEvent(new CustomEvent('snackbar:close', { bubbles: true, composed: true }));
  }

  private handleActionClick(): void {
    this.dispatchEvent(new CustomEvent('snackbar:action-click', { bubbles: true, composed: true }));
  }

  private handleButtonClick(): void {
    this.handleActionClick();
    this.handleClose();
  }

  override updated(changedProperties: Map<string, unknown>): void {
    if (changedProperties.has('open') || changedProperties.has('autoHideTimeout')) {
      clearTimeout(this.timeoutId);
      if (this.open) {
        this.timeoutId = setTimeout(() => {
          this.handleClose();
        }, this.autoHideTimeout) as unknown as number;
      }
    }
  }

  override disconnectedCallback(): void {
    clearTimeout(this.timeoutId);
    super.disconnectedCallback();
  }

  override render() {
    if (!this.open) return nothing;

    const containerStyles = styleMap({
      '--snackbar-z-index': '1000',
      '--snackbar-background-color': resolveThemeColor(this.severity, 'regular'),
    });

    const progressBarStyles = styleMap({
      animationDuration: `${this.autoHideTimeout}ms`,
      background: resolveThemeColor(this.severity, 'active'),
    });

    return html`
      <div class="snack-container" style=${containerStyles} data-testid="snackbar">
        <div class="snack-content">
          <icon-wc size="large" icon=${icons[this.severity]} color="gray6"></icon-wc>
          <zx-text color="gray6" overflow="break-word">${this.label}</zx-text>
          <zx-button
            label=${this.actionLabel}
            type="ghost"
            color="gray6"
            @click=${this.handleButtonClick}
          ></zx-button>
        </div>
        <div class="progress-bar" style=${progressBarStyles} data-testid="progress-bar"></div>
      </div>
    `;
  }
}

if (!customElements.get('zx-snackbar')) {
  customElements.define('zx-snackbar', ZxSnackbar);
}

declare global {
  interface HTMLElementTagNameMap {
    'zx-snackbar': SnackbarWC;
  }
}

// src/ui-components/components/Snackbar.tsx
/*
 * SPDX-FileCopyrightText: 2021 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import '../web-components/ds-icon';

import React, { useCallback, useEffect } from 'react';

import { resolveThemeColor } from '../theme/theme-utils';
import { type IconName } from '../web-components/icon-registry';
import { TIMERS } from './constants';
import styles from './Snackbar.module.css';

const icons: Record<'success' | 'info' | 'warning' | 'error', IconName> = {
  success: 'CheckmarkOutline',
  info: 'InfoOutline',
  warning: 'AlertTriangleOutline',
  error: 'CloseCircleOutline',
};

type SnackbarProps = {
  /** Whether to show the Snackbar or not */
  open?: boolean;
  /** Snackbar severity */
  severity?: 'success' | 'info' | 'warning' | 'error';
  /** Snackbar text message */
  label: string | React.ReactElement;
  /** Snackbar button text */
  actionLabel?: string;
  /** Button's click callback */
  onActionClick?: () => void;
  /** Callback to handle Snackbar closing */
  onClose?: () => void;
  /** autoHide timing in milliseconds */
  autoHideTimeout?: number;
};

const Snackbar = ({
  open = false,
  severity = 'info',
  label,
  actionLabel = 'Ok',
  onActionClick,
  onClose,
  autoHideTimeout = TIMERS.SNACKBAR.DEFAULT_HIDE_TIMEOUT,
}: SnackbarProps) => {
  const handleClick = useCallback(() => {
    if (onActionClick) {
      onActionClick();
    } else if (onClose) {
      onClose();
    }
  }, [onActionClick, onClose]);

  const enableTimeout = open && onClose !== undefined;

  useEffect(() => {
    let timeout: number;
    if (enableTimeout) {
      timeout = setTimeout(() => {
        onClose();
      }, autoHideTimeout) as unknown as number;
    }
    return (): void => {
      clearTimeout(timeout);
    };
  }, [onClose, autoHideTimeout, enableTimeout]);

  if (!open) return null;

  return (
    <div
      className={styles.snackContainer}
      style={
        {
          '--snackbar-z-index': 1000,
          '--snackbar-background-color': resolveThemeColor(severity, 'regular'),
        } as React.CSSProperties
      }
      data-testid="snackbar"
    >
      <div className={styles.snackContent}>
        <ds-icon size="large" icon={icons[severity]} color="gray6"></ds-icon>
        <ds-text color="gray6" overflow="break-word">
          {label}
        </ds-text>
        <ds-button label={actionLabel} type="ghost" color="gray6" onClick={handleClick} />
      </div>
      {enableTimeout && (
        <div
          className={styles.progressBar}
          style={{
            animationDuration: `${autoHideTimeout}ms`,
            background: resolveThemeColor(severity, 'active'),
          }}
          data-testid="progress-bar"
        />
      )}
    </div>
  );
};

export { Snackbar };
